services:
  auth_db:
    image: postgres:16-alpine
    container_name: auth_ms_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_AUTHDB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_AUTHDB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_AUTHDB_DB}
    ports:
      - "${POSTGRES_AUTHDB_PORT}:5432"
    networks:
      - ecommerce-network
    volumes:
      - auth_data:/var/lib/postgresql/data

  customer_db:
    image: postgres:16-alpine
    container_name: customer_ms_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_CUSTOMERDB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_CUSTOMERDB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_CUSTOMERDB_DB}
    ports:
      - "${POSTGRES_CUSTOMERDB_PORT}:5432"
    networks:
      - ecommerce-network
    volumes:
      - customers_data:/var/lib/postgresql/data

  order_db:
    image: postgres:16-alpine
    container_name: order_ms_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_ORDERDB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_ORDERDB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_ORDERDB_DB}
    ports:
      - "${POSTGRES_ORDERDB_PORT}:5432" # Puerto ${POSTGRES_ORDERDB_PORT} para no chocar con el de productos
    networks:
      - ecommerce-network
    volumes:
      - orders_data:/var/lib/postgresql/data

  product_db:
    image: postgres:16-alpine
    container_name: product_ms_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_PRODUCTDB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PRODUCTDB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_PRODUCTDB_DB}
    ports:
      - "${POSTGRES_PRODUCTDB_PORT}:5432"
    networks:
      - ecommerce-network
    volumes:
      - products_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: ecommerce_ms_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - auth_db
      - customer_db
      - product_db
      - order_db
    networks:
      - ecommerce-network
    volumes:
      - ./servers.json:/pgadmin4/servers.json

networks:
  ecommerce-network:
    driver: bridge

volumes:
  products_data:
  orders_data:
  customers_data:
  auth_data:
