version: '3.8'

services:
  auth_db:
    image: postgres:16-alpine
    container_name: auth_ms_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: authdb
    ports:
      - "5432:5432"
    networks:
      - ecommerce-network
    volumes:
      - auth_data:/var/lib/postgresql/data

  customer_db:
    image: postgres:16-alpine
    container_name: customer_ms_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: customerdb
    ports:
      - "5433:5432"
    networks:
      - ecommerce-network
    volumes:
      - customers_data:/var/lib/postgresql/data

  order_db:
    image: postgres:16-alpine
    container_name: order_ms_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: orderdb
    ports:
      - "5434:5432" # Puerto 5434 para no chocar con el de productos
    networks:
      - ecommerce-network
    volumes:
      - orders_data:/var/lib/postgresql/data

  product_db:
    image: postgres:16-alpine
    container_name: product_ms_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5435:5432"
    networks:
      - ecommerce-network
    volumes:
      - products_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: ecommerce_ms_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - product_db
      - order_db
    networks:
      - ecommerce-network
    volumes:
      - ./servers.json:/pgadmin4/servers.json

networks:
  ecommerce-network:
    driver: bridge

volumes:
  products_data:
  orders_data:
  customers_data:
  auth_data:
