server:
  port: 8761 # Puerto por defecto de Eureka

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false # No se registra a sí mismo
    fetch-registry: false       # No necesita descargar el registro