server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Ruta para el Microservicio de Productos
        - id: product-microservice
          uri: lb://product-microservice # "lb://" le dice que use Load Balancing vía Eureka
          predicates:
            - Path=/api/v1/products/**

        # Ruta para el Microservicio de Órdenes
        - id: order-microservice
          uri: lb://order-microservice
          predicates:
            - Path=/api/v1/orders/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/