server:
  port: 8761

management:
    endpoints:
        web:
            exposure:
                include: health, info, prometheus
    endpoint:
        health:
            show-details: always

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false 
    fetch-registry: false       
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/